version: "3.9"

services:
  neo4j:
    image: neo4j:5.2
    ports:
      # http
      - target: 7474
        published: 7474
      # bolt
      - target: 7687
        published: 7687
    volumes:
      - type: volume
        source: neo4j_data
        target: /data
      - type: volume
        source: neo4j_logs
        target: /logs
    environment:
      NEO4J_AUTH: neo4j/password

volumes:
  neo4j_data:
  neo4j_logs:
